- name: enable systemd-networkd
  systemd:
    name: systemd-networkd
    enabled: yes
    state: restarted
    daemon_reload: yes
  listen: "start and enable systemd-networkd"

- name: use systemd-resolved
  file:
    src: /run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    state: link
    force: Yes
  listen: "use systemd-resolved"
