- name: restart sssd
  service: name=sssd state=restarted enabled=yes
  listen: "restart sssd"

- name: reload systemd
  systemd:
    daemon_reload: yes
  listen: "reload systemd"

- name: restart rpc-gssd
  systemd:
    name: rpc-gssd
    state: restarted
  notify: "restart rpc-gssd"
