- name: restart krb5-kdc
  service: name=krb5-kdc state=restarted enabled=yes
  listen: "restart krb5-kdc"

- name: restart krb5-admin-server
  service: name=krb5-admin-server state=restarted enabled=yes
  listen: "restart krb5-admin-server"
