## generate most of this list with 'tasksel --task-packages standard'
cont_packages:
  - systemd-container
  - openssh-server
  - sudo
  - python3
  - auto-apt-proxy

  - bash-completion
  - bind9-dnsutils
  - file
  - locales
  - xz-utils
  - lsof
  - wget
  - bind9-host
  - man-db
  - ca-certificates
  - manpages
  - libc-l10n
  - traceroute
  - bzip2
  - netcat-traditional
  - telnet
