- name: restart networking
  service: name=networking state=restarted enabled=yes
  listen: restart networking

- name: restart shorewall
  service: name=shorewall state=restarted enabled=yes
  listen: restart shorewall
