- name: restart networking
  systemd: name=networking state=restarted enabled=yes
  listen: restart networking
  when: not run_in_installer|default(false)|bool

- name: start firewalld
  systemd: name=firewalld state=started enabled=yes
  listen: "start firewalld"
  when: not run_in_installer|default(false)|bool
