- name: restart apache2
  systemd:
    name: apache2
    state: restarted
  listen: "restart apache2"

- name: restart php-fpm
  systemd:
    name: php{{ php_ver.stdout }}-fpm
    state: restarted
  listen: "restart php-fpm"
