---
kdc_master_pwd: "{{ lookup('password', '/tmp/kdc_master.pwd length=24') }}"
kdc_master_pwd_file: "/root/kdc-master.pwd"

kdc_service_pwd: "{{ lookup('password', '/tmp/kdc-service.pwd length=24') }}"
kadmin_service_pwd: "{{ lookup('password', '/tmp/kadmin-service.pwd length=24') }}"

kadmin_pwd: "{{ lookup('password', '/tmp/kadmin.pwd length=24') }}"
kadmin_pwd_file: "/root/kadmin.pwd"
