- name: rebuild di-netboot-assistant menu
  command: "{{ item }}"
  with_items:
    - di-netboot-assistant rebuild-menu
    - di-netboot-assistant rebuild-grub
  listen: rebuild di-netboot-assistant menu
