- name: run update-grub
  command: update-grub
  listen: update grub

- name: reload NetworkManager
  when: not run_in_installer|default(false)|bool
  systemd:
    daemon_reload: yes
    name: NetworkManager
    state: reloaded
    enabled: yes
  listen: reload NetworkManager

# fails in installer with stretch, workaround below:
#- name: enable tmp.mount
#  systemd:
#    daemon_reload: yes
#    name: tmp.mount
#    enabled: yes

- name: make sure local-fs.target.wants exists
  file: path=/etc/systemd/system/local-fs.target.wants/ state=directory
  listen: enable tmp.mount

- name: enable tmp.mount
  file:
    src: /etc/systemd/system/tmp.mount
    dest: /etc/systemd/system/local-fs.target.wants/tmp.mount
    state: link
  listen: enable tmp.mount
